import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;

var modIDs as string[] = [
    "ic2",
];

var exclude as IIngredient[] = [
    <ic2:crafting:1>,
    <ic2:resource:4>,
    <ic2:ingot:8>,
    <ic2:crafting:0>,
    <ic2:rubber_wood>,
    <ic2:leaves>,
    <ic2:sapling>,
    <ic2:resource:1>,
	<ic2:resource:2>,
	<ic2:resource:3>,
    <ic2:resource:5>,
    <ic2:resource:6>,
    <ic2:resource:7>,
    <ic2:resource:8>,
    <ic2:resource:9>,
    <ic2:resource:15>,
    <ic2:plate:0>,
    <ic2:plate:1>,
    <ic2:plate:2>,
    <ic2:plate:3>,
    <ic2:plate:5>,
    <ic2:plate:6>,
    <ic2:plate:7>,
    <ic2:plate:8>,
    <ic2:crafting:4>,
    <ic2:crafting:13>,
    <ic2:crafting:14>,
    <ic2:crafting:15>,
    <ic2:ingot:0>,
	<ic2:ingot:1>,
	<ic2:ingot:2>,
	<ic2:ingot:3>,
	<ic2:ingot:4>,
	<ic2:ingot:5>,
	<ic2:ingot:6>,
    <ic2:ingot:7>,
    <ic2:crafting:2>,
    <ic2:te:2>,
    <ic2:te:6>,
    <ic2:te:14>,
    <ic2:te:18>,
    <ic2:te:22>,
    <ic2:te:23>,
    <ic2:te:24>,
    <ic2:te:25>,
    <ic2:te:26>,
    <ic2:te:34>,
    <ic2:te:39>,
    <ic2:te:40>,
    <ic2:te:48>,
    <ic2:te:49>,
    <ic2:te:51>,
    <ic2:te:52>,
    <ic2:te:54>,
    <ic2:te:56>,
    <ic2:te:57>,
    <ic2:te:58>,
    <ic2:te:59>,
    <ic2:te:60>,
    <ic2:te:61>,
    <ic2:te:62>,
    <ic2:te:63>,
    <ic2:te:64>,
    <ic2:te:70>,
    <ic2:te:71>,
    <ic2:te:74>,
    <ic2:te:75>,
    <ic2:te:78>,
    <ic2:te:79>,
    <ic2:te:80>,
    <ic2:te:84>,
    <ic2:te:85>,
    <ic2:te:88>,
    <ic2:te:89>,
    <ic2:te:92>,
    <ic2:te:93>,
    <ic2:resource:13>,
    <ic2:energy_pack>.withTag({charge: 2000000.0}),
    <ic2:energy_pack:26>,
    <ic2:hazmat_helmet>,
    <ic2:hazmat_chestplate>,
    <ic2:hazmat_leggings>,
    <ic2:jetpack_electric>.withTag({charge: 30000.0}),
    <ic2:jetpack_electric:26>,
    <ic2:lappack>.withTag({charge: 2.0E7}),
    <ic2:lappack:26>,
    <ic2:nano_boots>.withTag({charge: 1000000.0}),
    <ic2:nano_boots:26>,
    <ic2:nano_chestplate>.withTag({charge: 1000000.0}),
    <ic2:nano_chestplate:26>,
    <ic2:nano_helmet>.withTag({charge: 1000000.0}),
    <ic2:nano_helmet:26>,
    <ic2:nano_leggings>.withTag({charge: 1000000.0}),
    <ic2:nano_leggings:26>,
    <ic2:nightvision_goggles>.withTag({charge: 200000.0}),
    <ic2:nightvision_goggles:26>,
    <ic2:quantum_boots>.withTag({charge: 1.0E7}),
    <ic2:quantum_boots:26>,
    <ic2:quantum_chestplate>.withTag({charge: 1.0E7}),
    <ic2:quantum_chestplate:26>,
    <ic2:quantum_helmet>.withTag({charge: 1.0E7}),
    <ic2:quantum_helmet:26>,
    <ic2:quantum_leggings>.withTag({charge: 1.0E7}),
    <ic2:quantum_leggings:26>,
    <ic2:nuclear:0>,
    <ic2:nuclear:1>,
    <ic2:nuclear:3>,
    <ic2:nuclear:4>,
    <ic2:nuclear:5>,
    <ic2:nuclear:7>,
    <ic2:nuclear:8>,
    <ic2:nuclear:9>,
    <ic2:nuclear:10>,
    <ic2:nuclear:11>,
    <ic2:nuclear:12>,
    <ic2:nuclear:13>,
    <ic2:nuclear:14>,
    <ic2:nuclear:15>,
    <ic2:nuclear:16>,
    <ic2:misc_resource:3>,
    <ic2:crafting:9>,
    <ic2:crafting:12>,
    <ic2:crafting:23>,
    <ic2:crafting:24>,
    <ic2:crafting:27>,
    <ic2:crafting:37>,
    <ic2:block_cutting_blade>,
    <ic2:block_cutting_blade:1>,
    <ic2:block_cutting_blade:2>,
    <ic2:upgrade_kit>,
    <ic2:energy_crystal>.withTag({charge: 1000000.0}),
    <ic2:energy_crystal:26>,
    <ic2:lapotron_crystal>.withTag({charge: 1.0E7}),
    <ic2:lapotron_crystal:26>,
    <ic2:advanced_charging_re_battery>.withTag({charge: 400000.0}),
    <ic2:advanced_charging_re_battery:26>,
    <ic2:charging_energy_crystal>.withTag({charge: 4000000.0}),
    <ic2:charging_energy_crystal:26>,
    <ic2:charging_lapotron_crystal>.withTag({charge: 4.0E7}),
    <ic2:charging_lapotron_crystal:26>,
    <ic2:heat_storage>.withTag({advDmg: 0}),
    <ic2:tri_heat_storage>.withTag({advDmg: 0}),
    <ic2:hex_heat_storage>.withTag({advDmg: 0}),
    <ic2:plating>,
    <ic2:heat_plating>,
    <ic2:containment_plating>,
    <ic2:heat_exchanger>.withTag({advDmg: 0}),
    <ic2:reactor_heat_exchanger>.withTag({advDmg: 0}),
    <ic2:component_heat_exchanger>.withTag({advDmg: 0}),
    <ic2:advanced_heat_exchanger>.withTag({advDmg: 0}),
    <ic2:heat_vent>.withTag({advDmg: 0}),
    <ic2:reactor_heat_vent>.withTag({advDmg: 0}),
    <ic2:overclocked_heat_vent>.withTag({advDmg: 0}),
    <ic2:component_heat_vent>.withTag({advDmg: 0}),
    <ic2:advanced_heat_vent>.withTag({advDmg: 0}),
    <ic2:neutron_reflector>.withTag({advDmg: 0}),
    <ic2:thick_neutron_reflector>.withTag({advDmg: 0}),
    <ic2:iridium_reflector>.withTag({advDmg: 0}),
    <ic2:rsh_condensator>.withTag({advDmg: 0}),
    <ic2:lzh_condensator>.withTag({advDmg: 0}),
    <ic2:heatpack>,
    <ic2:uranium_fuel_rod>.withTag({advDmg: 0}),
    <ic2:dual_uranium_fuel_rod>.withTag({advDmg: 0}),
    <ic2:quad_uranium_fuel_rod>.withTag({advDmg: 0}),
    <ic2:mox_fuel_rod>.withTag({advDmg: 0}),
    <ic2:dual_mox_fuel_rod>.withTag({advDmg: 0}),
    <ic2:quad_mox_fuel_rod>.withTag({advDmg: 0}),
    <ic2:lithium_fuel_rod>.withTag({advDmg: 0}),
    <ic2:depleted_isotope_fuel_rod>.withTag({advDmg: 0}),
    <ic2:tfbp:*>,
    <ic2:frequency_transmitter>,
    <ic2:containment_box>,
    <ic2:advanced_scanner>.withTag({charge: 1000000.0}),
    <ic2:advanced_scanner:26>,
    <ic2:chainsaw>.withTag({charge: 30000.0}),
    <ic2:chainsaw:26>,
    <ic2:diamond_drill>.withTag({charge: 30000.0}),
    <ic2:diamond_drill:26>,
    <ic2:drill>.withTag({charge: 30000.0}),
    <ic2:drill:26>,
    <ic2:iridium_drill>.withTag({charge: 300000.0}),
    <ic2:iridium_drill:26>,
    <ic2:mining_laser>.withTag({charge: 300000.0}),
    <ic2:mining_laser:26>,
    <ic2:nano_saber>.withTag({charge: 160000.0}),
    <ic2:nano_saber:26>,
    <ic2:obscurator>.withTag({charge: 100000.0}),
    <ic2:obscurator:26>,
    <ic2:scanner>.withTag({charge: 100000.0}),
    <ic2:scanner:26>,
    <ic2:cable:1>.withTag({type: 1 as byte, insulation: 0 as byte}),
    <ic2:cable:2>.withTag({type: 2 as byte, insulation: 0 as byte}),
    <ic2:cable:2>.withTag({type: 2 as byte, insulation: 1 as byte}),
    <ic2:cable:2>.withTag({type: 2 as byte, insulation: 2 as byte}),
    <ic2:cable:3>.withTag({type: 3 as byte, insulation: 0 as byte}),
    <ic2:cable:3>.withTag({type: 3 as byte, insulation: 1 as byte}),
    <ic2:cable:3>.withTag({type: 3 as byte, insulation: 2 as byte}),
    <ic2:cable:3>.withTag({type: 3 as byte, insulation: 3 as byte}),
    <ic2:cable:5>.withTag({type: 5 as byte, insulation: 0 as byte}),
    <ic2:cable:5>.withTag({type: 6 as byte, insulation: 0 as byte}),
    <ic2:upgrade:0>,
    <ic2:upgrade:1>,
    <ic2:upgrade:2>,
    <ic2:upgrade:3>,
    <ic2:upgrade:4>,
    <ic2:upgrade:5>,
    <ic2:upgrade:6>,
    <ic2:upgrade:7>,
    <ic2:upgrade:8>,
    <ic2:upgrade:9>,
    <ic2:dynamite>,
    <ic2:dynamite_sticky>,
    <ic2:remote>,
    <ic2:crystal_memory>,
    <ic2:te:82>,
    <ic2:te:86>,
    <ic2:dust:0>,
    <ic2:dust:2>,
    <ic2:dust:4>,
    <ic2:dust:7>,
    <ic2:dust:8>,
    <ic2:dust:10>,
    <ic2:dust:14>,
    <ic2:dust:16>,
    <ic2:dust:17>,
    <ic2:crafting:3>,
    <ic2:crop_stick>,
    <ic2:crop_res:0>,
    <ic2:crop_res:1>,
    <ic2:crop_res:2>,
    <ic2:crop_res:3>,
    <ic2:crop_res:4>,
    <ic2:crop_res:5>,
    <ic2:terra_wart>,
    <ic2:cropnalyzer>,
    <ic2:weeding_trowel>,
    <ic2:booze_mug>,
    <ic2:debug_item>,
    <ic2:crop_seed_bag>,
];

for id in modIDs{
    for item in loadedMods[id].items{
        logger.logInfo(item.name);
        var valid = true;
        for excluded in exclude {
            if (excluded.matchesExact(item)){
                valid = false;
            }
        }
        if valid {
            mods.ItemStages.addItemStage("ic2_basic", item);
        }
    }
}

var stagedItems as IItemStack[] = [
];

for item in stagedItems {
	mods.ItemStages.addItemStage("ic2_basic", item);
}